#!/bin/bash
# Blocks hand-edits to OpenAPI-generated client sources; they're regenerated by
# `./gradlew :client:openApiGenerate` from client/build.gradle.kts's pinned inputSpec.
INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

if [[ "$FILE_PATH" == *"client/build/generated/openapi/"* ]]; then
  echo "Blocked: $FILE_PATH is generated by './gradlew :client:openApiGenerate' — never hand-edited. Change the OpenAPI spec (client/specs/) or generator config in client/build.gradle.kts instead." >&2
  exit 2
fi
exit 0
