# docker compose up -d
services:
  mariadb:
    image: mariadb
    container_name: 'mariadb_blackhole'
    ports:
      - "3336:3306"
    shm_size: 128mb
    environment:
      MARIADB_ROOT_PASSWORD: blackhole
      MARIADB_DATABASE: blackhole
    volumes:
      - ./mariadb/data/:/var/lib/mysql
    networks:
      - blackhole_go_net
  rabbitmq:
    image: rabbitmq:3
    container_name: 'rabbitmq_blackhole'
    networks:
      - blackhole_go_net
    shm_size: 128mb
    ports:
      - "5672:5672"
      - "8880:15672"

networks:
  blackhole_go_net:
    driver: bridge
