-- Evidence attached to a punishment (Phase 2 of the roadmap): a hash/reference plus a bounded
-- retention window, not the raw content itself, so evidence storage stays DSGVO-compliant by
-- default. Generated by temporarily running Hibernate's hbm2ddl.auto=update against a scratch
-- database and capturing the resulting DDL, matching the technique used for V1__baseline.sql.

CREATE TABLE `punishment_evidence` (
  `identifier` uuid NOT NULL,
  `captured_content_hash` varchar(255) DEFAULT NULL,
  `evidence_type` tinyint(4) DEFAULT NULL CHECK (`evidence_type` between 0 and 3),
  `meta_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`meta_data`)),
  `reference_id` varchar(255) DEFAULT NULL,
  `retention_expires_at` bigint(20) DEFAULT NULL,
  `tenant_id` uuid DEFAULT NULL,
  `punishment_identifier` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`identifier`),
  KEY `IDXeowdvehtn2mq9ratnjjt10mx0` (`identifier`),
  KEY `IDX88plc6lylknnkler3ds0vmagv` (`tenant_id`),
  KEY `FK1fcfw3b9ah8l5ywj1ksemk98r` (`punishment_identifier`),
  CONSTRAINT `FK1fcfw3b9ah8l5ywj1ksemk98r` FOREIGN KEY (`punishment_identifier`) REFERENCES `punishments` (`identifier`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
