-- Player reports (Phase 3 of the roadmap). created_at/updated_at are real bigint columns, not
-- JSON metaData entries, so the report-submission rate limit can filter on them directly.
-- Generated by temporarily running Hibernate's hbm2ddl.auto=update against a scratch database
-- and capturing the resulting DDL, matching the technique used for V1/V2.

CREATE TABLE `reports` (
  `identifier` uuid NOT NULL,
  `category` tinyint(4) DEFAULT NULL CHECK (`category` between 0 and 3),
  `created_at` bigint(20) NOT NULL,
  `description` varchar(1000) DEFAULT NULL,
  `meta_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`meta_data`)),
  `reported_hash` varchar(255) DEFAULT NULL,
  `reporter_hash` varchar(255) DEFAULT NULL,
  `resolution_note` varchar(1000) DEFAULT NULL,
  `resolved_by` uuid DEFAULT NULL,
  `status` tinyint(4) DEFAULT NULL CHECK (`status` between 0 and 3),
  `tenant_id` uuid DEFAULT NULL,
  `updated_at` bigint(20) NOT NULL,
  PRIMARY KEY (`identifier`),
  KEY `IDXcdecaabcx0057rmwougq4lln8` (`identifier`),
  KEY `IDXp2ffpn85f33jnlh9a6dw6dfjd` (`tenant_id`),
  KEY `IDXhucb8heess4o7s9d641njq2e0` (`reporter_hash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

CREATE TABLE `report_evidence_references` (
  `report_identifier` uuid NOT NULL,
  `evidence_identifier` uuid DEFAULT NULL,
  KEY `FK27b8gnu183fwcp3f8ixk9xw49` (`report_identifier`),
  CONSTRAINT `FK27b8gnu183fwcp3f8ixk9xw49` FOREIGN KEY (`report_identifier`) REFERENCES `reports` (`identifier`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
