-- Generic third-party connector framework (Phase 4 of the roadmap). Generated by temporarily
-- running Hibernate's hbm2ddl.auto=update against a scratch database and capturing the
-- resulting DDL, matching the technique used for V1-V3.

CREATE TABLE `connector_registrations` (
  `identifier` uuid NOT NULL,
  `meta_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`meta_data`)),
  `name` varchar(255) DEFAULT NULL,
  `oauth2_client_id` varchar(255) DEFAULT NULL,
  `oauth2_client_secret_hash` varchar(255) DEFAULT NULL,
  `status` tinyint(4) DEFAULT NULL CHECK (`status` between 0 and 1),
  `tenant_id` uuid DEFAULT NULL,
  PRIMARY KEY (`identifier`),
  UNIQUE KEY `UKhb72u55ks7duissu086wfgjd4` (`oauth2_client_id`),
  KEY `IDXp64mq4clkp3b1d9c6jmo06021` (`identifier`),
  KEY `IDXhwsvcq9wogcnjafm8qmil9niy` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

CREATE TABLE `connector_scopes` (
  `connector_identifier` uuid NOT NULL,
  `scope` varchar(255) DEFAULT NULL,
  KEY `FK2w8vnnh1hjq9qy8dgny2uwgbt` (`connector_identifier`),
  CONSTRAINT `FK2w8vnnh1hjq9qy8dgny2uwgbt` FOREIGN KEY (`connector_identifier`) REFERENCES `connector_registrations` (`identifier`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

CREATE TABLE `event_subscriptions` (
  `identifier` uuid NOT NULL,
  `active` bit(1) NOT NULL,
  `delivery_url` varchar(255) DEFAULT NULL,
  `failure_count` int(11) NOT NULL,
  `last_attempt_at` bigint(20) DEFAULT NULL,
  `last_success_at` bigint(20) DEFAULT NULL,
  `meta_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`meta_data`)),
  `signing_secret` varchar(255) DEFAULT NULL,
  `connector_identifier` uuid DEFAULT NULL,
  PRIMARY KEY (`identifier`),
  KEY `IDX4ja81yhw8rl240tcyebtjgvx4` (`identifier`),
  KEY `FKsp913s457jgefhadxb9p06qyo` (`connector_identifier`),
  CONSTRAINT `FKsp913s457jgefhadxb9p06qyo` FOREIGN KEY (`connector_identifier`) REFERENCES `connector_registrations` (`identifier`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

CREATE TABLE `event_subscription_types` (
  `subscription_identifier` uuid NOT NULL,
  `event_type` varchar(255) DEFAULT NULL,
  KEY `FKrtito3r91kmi2qej9acwox35h` (`subscription_identifier`),
  CONSTRAINT `FKrtito3r91kmi2qej9acwox35h` FOREIGN KEY (`subscription_identifier`) REFERENCES `event_subscriptions` (`identifier`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
