-- Dual-ELO system (Phase 5 of the roadmap): two independent chat/gameplay tracks plus an
-- append-only audit trail. Generated by temporarily running Hibernate's hbm2ddl.auto=update
-- against a scratch database and capturing the resulting DDL, matching the technique used
-- for V1-V4.

CREATE TABLE `elo_profiles` (
  `owner` varchar(255) NOT NULL,
  `tenant_id` uuid NOT NULL,
  `chat_elo` int(11) NOT NULL,
  `chat_elo_updated_at` bigint(20) NOT NULL,
  `gameplay_elo` int(11) NOT NULL,
  `gameplay_elo_updated_at` bigint(20) NOT NULL,
  `meta_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`meta_data`)),
  PRIMARY KEY (`owner`,`tenant_id`),
  KEY `IDX5k6jltfkea67v5ai92cey03u7` (`owner`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

CREATE TABLE `elo_events` (
  `identifier` uuid NOT NULL,
  `created_at` bigint(20) NOT NULL,
  `delta` int(11) NOT NULL,
  `meta_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`meta_data`)),
  `owner` varchar(255) DEFAULT NULL,
  `reason_code` tinyint(4) DEFAULT NULL CHECK (`reason_code` between 0 and 5),
  `resulting_score` int(11) NOT NULL,
  `source_evidence_id` uuid DEFAULT NULL,
  `tenant_id` uuid DEFAULT NULL,
  `track` tinyint(4) DEFAULT NULL CHECK (`track` between 0 and 1),
  PRIMARY KEY (`identifier`),
  KEY `IDX1vli9egxhskmxh09x7ippe01p` (`identifier`),
  KEY `IDXbi03h5v8mngaibmc7f6eo81s3` (`tenant_id`),
  KEY `IDX8kfktno2r37fryp23hbrywxge` (`owner`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
