-- Appeal workflow (Phase 6 of the roadmap). created_at/updated_at are real bigint columns, not
-- JSON metaData entries, same reasoning as V3__reports.sql - the minimum-time-since-punishment
-- eligibility check needs to filter on them directly. Generated by temporarily running
-- Hibernate's hbm2ddl.auto=update against a scratch database and capturing the resulting DDL,
-- matching the technique used for V1-V5.

CREATE TABLE `appeals` (
  `identifier` uuid NOT NULL,
  `appellant_hash` varchar(255) DEFAULT NULL,
  `created_at` bigint(20) NOT NULL,
  `decided_by` uuid DEFAULT NULL,
  `decision_note` varchar(2000) DEFAULT NULL,
  `eligibility_check_result` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`eligibility_check_result`)),
  `meta_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`meta_data`)),
  `statement` varchar(2000) DEFAULT NULL,
  `status` tinyint(4) DEFAULT NULL CHECK (`status` between 0 and 6),
  `tenant_id` uuid DEFAULT NULL,
  `updated_at` bigint(20) NOT NULL,
  `punishment_identifier` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`identifier`),
  KEY `IDXkumdsu9qt44a38mg4k9ngyp87` (`identifier`),
  KEY `IDX7yn6lv2wptlia206ij210jtig` (`tenant_id`),
  KEY `IDX9faypy3gxh4xmiqii41ypsj5k` (`appellant_hash`),
  KEY `FKqb76lk2ldlufmeevnpme8l94m` (`punishment_identifier`),
  CONSTRAINT `FKqb76lk2ldlufmeevnpme8l94m` FOREIGN KEY (`punishment_identifier`) REFERENCES `punishments` (`identifier`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
