-- Ban-evasion detection (Phase 7 of the roadmap). `token` is HMAC-SHA512(ip, server-held salt) -
-- a keyed hash, never the raw IP. This table is itself personal data and has its own retention
-- window (see IpCorrelationRetentionSweeper), separate from any punishment/profile retention.
-- Generated by temporarily running Hibernate's hbm2ddl.auto=update against a scratch database
-- and capturing the resulting DDL, matching the technique used for V1-V6.

CREATE TABLE `ip_correlation_tokens` (
  `identifier` uuid NOT NULL,
  `first_seen` bigint(20) NOT NULL,
  `last_seen` bigint(20) NOT NULL,
  `meta_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`meta_data`)),
  `occurrence_count` int(11) NOT NULL,
  `owner_hash` varchar(255) DEFAULT NULL,
  `tenant_id` uuid DEFAULT NULL,
  `token` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`identifier`),
  KEY `IDXej580909u0b2cronpaairkgty` (`identifier`),
  KEY `IDXb4n6xf0005sm3973m6oyxrw1t` (`tenant_id`),
  KEY `IDXdchy5i8x4p42k38necseou23o` (`token`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
