-- Per-tenant fine-tuning of the dual-ELO system (Phase 5 follow-up): a tenant's base Elo,
-- perma-ban threshold, and perma-ban template per track, plus its report reward, override the
-- platform-wide defaults. Generated by temporarily running Hibernate's hbm2ddl.auto=update
-- against a scratch database and capturing the resulting DDL, matching the technique used
-- for V1-V7.

CREATE TABLE `tenant_elo_settings` (
  `tenant_id` uuid NOT NULL,
  `base_elo_chat` int(11) DEFAULT NULL,
  `base_elo_gameplay` int(11) DEFAULT NULL,
  `perma_ban_template_chat_id` uuid DEFAULT NULL,
  `perma_ban_template_gameplay_id` uuid DEFAULT NULL,
  `perma_ban_threshold_chat` int(11) DEFAULT NULL,
  `perma_ban_threshold_gameplay` int(11) DEFAULT NULL,
  `report_reward_delta` int(11) DEFAULT NULL,
  PRIMARY KEY (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

-- eloDelta on a punishment template: applied to the offender's Elo whenever the template is
-- used, regardless of who/what applied it (see PunishmentApplicationService.apply). 0 (the
-- default) means "no Elo effect" - every pre-existing template keeps its current behavior.
ALTER TABLE `punishment_templates` ADD COLUMN `elo_delta` int(11) NOT NULL DEFAULT 0;

-- EloReasonCode gained PUNISHMENT_APPLIED (6) and REPORT_REWARDED (7); the ordinal-backed
-- reason_code CHECK constraint from V5 must widen to admit them. Hibernate's schema-update
-- (used to capture the rest of this migration) does not touch existing CHECK constraints, so
-- this is hand-written; MariaDB requires MODIFY COLUMN to redefine a column-level inline CHECK
-- (DROP CONSTRAINT/DROP CHECK by the auto-generated name is rejected).
ALTER TABLE `elo_events` MODIFY COLUMN `reason_code` tinyint(4) DEFAULT NULL CHECK (`reason_code` between 0 and 7);
